In [51]:
import tensorflow as tf
import numpy as np

In [2]:
x = [1, 2, 3, 4, 5]

In [15]:
# create constant tensor
constant = tf.constant(x)
print(constant)
print(constant.ndim)
print(constant.shape)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
1
(5,)


In [18]:
# create variable tensor
variable = tf.Variable(x)
print(variable)
print(variable.shape)

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5])>
(5,)


In [21]:
# create random tensors
normal = tf.random.normal((2,2))
uniform = tf.random.uniform((2,2))
print(normal)
print(uniform)

tf.Tensor(
[[ 0.46771297  1.1439531 ]
 [-0.00468726 -1.1413215 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.9672353  0.55778396]
 [0.43863738 0.80427194]], shape=(2, 2), dtype=float32)


In [22]:
# create 2 same random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal((2,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal((2,2))

random_1 == random_2

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [24]:
# shuffle tensor
not_shuffled = tf.constant(x)
print(not_shuffled)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [44]:
shuffled = tf.random.shuffle(not_shuffled)
print(shuffled)

tf.Tensor([5 4 1 2 3], shape=(5,), dtype=int32)


In [46]:
# ones vale tensors
ones = tf.ones((2,2))
print(ones)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [50]:
# zeros vale tensors
zeros = tf.zeros((2,2))
print(zeros)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [49]:
# eye vale tensors
eye = tf.eye(2)
print(eye)

tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)


In [54]:
# arange vale tensors
_ = np.arange(10)
arange = tf.constant(_, shape=(2,5))
print(arange)

tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)


In [64]:
# total items in tensor
print(tf.size(arange))
# shape of tensor (it is basically the length of every dimension)
print(arange.shape)
# rank of tensor
print(arange.ndim)
# particular axis of tensor
print(arange[1, :])
# dtype of tensor
print(arange.dtype)

tf.Tensor(10, shape=(), dtype=int32)
(2, 5)
2
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int32)
<dtype: 'int32'>


In [69]:
# add dimension to tensor
# general tip  ** READ SHAPE FROM THE END TO FIGURE IT OUT
test = tf.ones((3,3))
print(test)
print()
test = tf.ones((3,3))
test = tf.expand_dims(test, axis=0)
print(test)
print()
test = tf.ones((3,3))
test = tf.expand_dims(test, axis=1)
print(test)
print()
test = tf.ones((3,3))
test = tf.expand_dims(test, axis=-1)
print(test)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 3, 3), dtype=float32)

tf.Tensor(
[[[1. 1. 1.]]

 [[1. 1. 1.]]

 [[1. 1. 1.]]], shape=(3, 1, 3), dtype=float32)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(3, 3, 1), dtype=float32)


In [72]:
# matrix multiplication
first = tf.random.uniform((3,2))
second = tf.random.uniform((2,3))
print(first)
print(second)

tf.Tensor(
[[0.1303196  0.72302616]
 [0.03500259 0.14889967]
 [0.45241117 0.4920081 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0.83751476 0.07739747 0.6869185 ]
 [0.20134604 0.9990591  0.06584918]], shape=(2, 3), dtype=float32)


In [75]:
print(tf.matmul(first, second))

tf.Tensor(
[[0.25472304 0.73243225 0.13712962]
 [0.05929554 0.15146868 0.03384885]
 [0.4779649  0.5265606  0.34316796]], shape=(3, 3), dtype=float32)


In [83]:
# aggregation
test = tf.constant([1,2,3,4,5], dtype=tf.float64)
print(tf.reduce_max(test))
print(tf.reduce_min(test))
print(tf.reduce_sum(test))
print(tf.reduce_mean(test))
print(tf.math.reduce_variance(test))
print(tf.math.reduce_std(test))

tf.Tensor(5.0, shape=(), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(15.0, shape=(), dtype=float64)
tf.Tensor(3.0, shape=(), dtype=float64)
tf.Tensor(2.0, shape=(), dtype=float64)
tf.Tensor(1.4142135623730951, shape=(), dtype=float64)


In [84]:
# argmax and argmin
print(tf.argmax(test))
print(tf.argmin(test))

tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)


In [85]:
# squeezing tensors
test = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,50))
print(test)

tf.Tensor(
[[[[0.43092024 0.54602635 0.14853084 0.9727237  0.31471384 0.26777327
    0.46807742 0.13167155 0.7261851  0.58768594 0.6064708  0.55267656
    0.447587   0.94949615 0.90005445 0.10014153 0.65893006 0.68291676
    0.75391304 0.19649065 0.17827892 0.17996705 0.6532538  0.43965352
    0.18706322 0.37094963 0.7931473  0.78418005 0.36796784 0.78121305
    0.77955294 0.64514494 0.6045432  0.39302325 0.74100244 0.20903671
    0.813516   0.5780213  0.22292185 0.7846714  0.6725931  0.22045875
    0.85959184 0.7394396  0.32487273 0.01440942 0.12737775 0.6955496
    0.39778352 0.1332438 ]]]], shape=(1, 1, 1, 50), dtype=float32)


In [86]:
test = tf.squeeze(test)
print(test)

tf.Tensor(
[0.43092024 0.54602635 0.14853084 0.9727237  0.31471384 0.26777327
 0.46807742 0.13167155 0.7261851  0.58768594 0.6064708  0.55267656
 0.447587   0.94949615 0.90005445 0.10014153 0.65893006 0.68291676
 0.75391304 0.19649065 0.17827892 0.17996705 0.6532538  0.43965352
 0.18706322 0.37094963 0.7931473  0.78418005 0.36796784 0.78121305
 0.77955294 0.64514494 0.6045432  0.39302325 0.74100244 0.20903671
 0.813516   0.5780213  0.22292185 0.7846714  0.6725931  0.22045875
 0.85959184 0.7394396  0.32487273 0.01440942 0.12737775 0.6955496
 0.39778352 0.1332438 ], shape=(50,), dtype=float32)
